server:
  port: 8761

eureka:
  instance:
    hostname: "${HOSTNAME:}.eureka"
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: "${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/}"